### ISSUE TITLE
Configuration reading using viper

### ISSUE THREAD

**Issue by lirm** [lirm/aeron-go#13]

**Comment by varun06** [comment]
I can work on this one. Let me know if that's fine. Also Viper can do many things, do you only need command line flag and env variables?

**Comment by lirm** [comment]
Hi @varun06, sorry for delay. I like to be careful in introducing 3rd party dependencies, so was really planning to explore what Viper can do for this project. This particular library is a client, so only env variables are used for feeding the parameters, but if those are carried over into the executable using it as command line - that's useful.

I'm completely open to exploring other features, but would like to remain conservative how deep it gets integrated.

**Comment by varun06** [comment]
Sure, that make total sense. I also avoid 3rd party dependency as much as I can.

**Comment by lirm** [comment]
Closing for now. Will reopen if there is a compelling argument for it.
