### ISSUE TITLE
missing code?

### ISSUE THREAD

**Issue by rogeralsing** [lirm/aeron-go#16]
Trying to compile I get these errors:

```
util\memmap\memmap.go:91: undefined: syscall.Mmap
util\memmap\memmap.go:91: undefined: syscall.PROT_READ
util\memmap\memmap.go:91: undefined: syscall.PROT_WRITE
util\memmap\memmap.go:91: undefined: syscall.MAP_SHARED
util\memmap\memmap.go:123: undefined: syscall.Mmap
util\memmap\memmap.go:123: undefined: syscall.PROT_READ
util\memmap\memmap.go:123: undefined: syscall.PROT_WRITE
util\memmap\memmap.go:123: undefined: syscall.MAP_SHARED
util\memmap\memmap.go:137: undefined: syscall.Munmap
```

Is there some missing file in the repo?

**Comment by lirm** [comment]
It's actually a problem I've seen trying to compile to Windows. I don't have a Windows env to use for development, so cannot debug the root problem. I'll try to search for possible solutions, but no guarantees.

**Comment by lirm** [comment]
Pull requests welcome!

**Comment by lirm** [comment]
An example of resolving this is at:
https://github.com/dvyukov/go-fuzz/issues/15
https://github.com/HouzuoGuo/tiedot/issues/7
https://github.com/dvyukov/go-fuzz/commit/5725488536b003c07e3141f5c61ebeb83e63eed1

Also reported by @khoxsey on Gitter

**Comment by lirm** [comment]
First attempt with https://github.com/lirm/aeron-go/tree/windows_mmap If it won't work, I'll just use https://github.com/edsrzf/mmap-go directly

**Comment by lirm** [comment]
This is now tracked in #23 and #24
