### ISSUE TITLE
CNC file corruption on Windows

### ISSUE THREAD

**Issue by khoxsey** [lirm/aeron-go#24]
Starting a go-based aeron client corrupts the CNC.dat file on Windows. It appears that something is mistakenly setting the first `int` in the file to `1`. The client then reports this error:
```
aeron cnc file version not understood: version=36503552
```
Upon restarting the driver, it throws the following:
```
Exception in thread "main" java.lang.IllegalStateException: aeron cnc file version not understood: version=1
        at io.aeron.CommonContext.isDriverActive(CommonContext.java:283)
        at io.aeron.driver.MediaDriver.ensureDirectoryIsRecreated(MediaDriver.java:402)
        at io.aeron.driver.MediaDriver.<init>(MediaDriver.java:162)
```

To replicate:
- clone AdaptiveConsulting/Aeron.NET and build the `Ping.exe` and `Pong.exe` samples
- start the media driver
- verify ping/pong, then shut them down so they don't interfere with aeron-go
- start the aeron-go Ping example, which should report the above version error
- stop the driver and check the file header of the CNC file. Its first int should be the value 1
- restart the driver, it should report the stack trace above

**Comment by lirm** [comment]
Just updated windows_mmap branch. Can you give it a shot?

**Comment by lirm** [comment]
Umm.. hold

**Comment by lirm** [comment]
Can you give this one a shot, please?

**Comment by khoxsey** [comment]
With the (minor) changes documented in #23, the `windows_mmap` branch builds but exhibits the same behavior, writing `1` to the CNC version. It appears to get farther into the process, with a new error:
```
$ ./ping.exe
panic: assignment to entry in nil map

goroutine 1 [running]:
panic(0x50ed60, 0xc04204e6d0)
        C:/Go/src/runtime/panic.go:500 +0x1af
github.com/lirm/aeron-go/aeron/util/memmap.doMap(0xc04207c030, 0x0, 0x600400, 0xc0420aa420, 0x3, 0x3)
        ~/go/src/github.com/lirm/aeron-go/aeron/util/memmap/map_windows.go:40 +0x176
github.com/lirm/aeron-go/aeron/util/memmap.MapExisting(0xc042056540, 0x39, 0x0, 0x0, 0x0, 0x0, 0x0)
        ~/go/src/github.com/lirm/aeron-go/aeron/util/memmap/memmap.go:88 +0x485
github.com/lirm/aeron-go/aeron/counters.MapFile(0xc042056540, 0x39, 0x23, 0x531725)
        ~/go/src/github.com/lirm/aeron-go/aeron/counters/counters.go:79 +0x13c
github.com/lirm/aeron-go/aeron.Connect(0xc0420928c0, 0x531b22)
        ~/go/src/github.com/lirm/aeron-go/aeron/aeron.go:63 +0x168
main.main()
        ~/go/src/github.com/lirm/aeron-go/examples/ping/ping.go:53 +0xc4
```

**Comment by lirm** [comment]
@khoxsey I've merged this into master to simplify maintenance. The changes are Windows specific and don't impact other platforms anyway. Please, test with latest master

**Comment by lirm** [comment]
I believe this one is fixed, so I'm closing it until I hear otherwise.
