### ISSUE TITLE
How to write /tmp/aeron-root/cnc.dat file

### ISSUE THREAD

**Issue by fnegyun** [lirm/aeron-go#28]
hi
when i use  aeron.NewContext().AeronDir("/tmp").MediaDriverTimeout(time.Second * 10)
i got an error:  Failed to map the file ./tmp/aeron-root/cnc.dat with zero size for existing file.
but i dont know how write a cnc.dat file。
can u give a  particular cnc.dat file for example?
thanks.

**Comment by lirm** [comment]
Sorry, for delay in responding.

cnc.dat file is created by driver, so you need to ensure that driver is up.

**Comment by lirm** [comment]
BTW, the code is out of date - it was based on 1.0 version. CNC version 5. Current version is 9. I've started work on updating the client. Planning to have it done in a few weeks.
