### ISSUE TITLE
Support for subscription by session-id

### ISSUE THREAD

**Issue by billsegall** [lirm/aeron-go#52]
This is partly a note to self as I'm about to take an extended holiday before implementing and partly an opportunity for comment.

For aeron-archive's ReplayMerge feature the aeron code uses subscriptions by session-id by establishing and looking up a publication.

To achieve this this, the Java implementation maintains a map of registrationIDs to the client conductors internal subscription objects. My intention is to rework the AddSubscription()/OnSubscriptionReady() to support this.

**Comment by billsegall** [comment]
Stan, If you felt ok giving me permissions to update issues I'd happy to assign this (and others) to myself and help manage the lifecycle.

**Comment by lirm** [comment]
@billsegall Yes, let me do that!

**Comment by ethanf** [comment]
This is completed and replay merge is implemented
