### ISSUE TITLE
How can a publication detect if there are connected subscribers?

### ISSUE THREAD

**Issue by ccnlui** [lirm/aeron-go#58]
The example shows the following method:
```go
if !publication.IsConnected() {
    log.Print("no subscribers detected")
}
```

But then there is also this comment:
```go
// IsConnected returns whether this publication is connected to the driver (not whether it has any Subscriptions)
func (pub *Publication) IsConnected() bool {
	return !pub.IsClosed() && pub.metaData.IsConnected.Get() == 1
}
```
I'm now very confused. How would a publication detect if there are active subscribers? 

Thank you.

**Comment by ethanf** [comment]
This is generally how Aeron works, not specific to go. https://github.com/real-logic/aeron/wiki might be helpful here

**Comment by ccnlui** [comment]
My point is that the print statement description seems like it's not reflecting how aeron behaves. It doesn't actually mean "no subscribers detected", instead it simply means it is not connected to the media driver, and has nothing to do with detecting subscribers, per the comment. Is this correct?

**Comment by ethanf** [comment]
This matches the Java implementation, you're right that the comment is a bit misleading.

https://github.com/real-logic/aeron/blob/master/aeron-client/src/main/java/io/aeron/Publication.java#L264

```java

    /**
     * Has the {@link Publication} seen an active Subscriber recently?
     *
     * @return true if this {@link Publication} has recently seen an active subscriber otherwise false.
     */
    public boolean isConnected()
    {
        return !isClosed && LogBufferDescriptor.isConnected(logMetaDataBuffer);
    }
```
