### ISSUE TITLE
Segmentation violation error dereferencing EndOfStreamPosOff in Close() in image.go

### ISSUE THREAD

**Issue by hcasalet** [lirm/aeron-go#74]
In Close() of aeron/image.go, lines 264-265, are setting the isEos of image: 
image.isEos = image.finalPosition >=
			image.logBuffers.Meta().EndOfStreamPosOff.Get()
However, image.logBuffers.Meta().EndOfStreamPosOff could be a nil pointer, and calling image.logBuffers.Meta().EndOfStreamPosOff.Get() resulted in a nil pointer dereferencing segmentation violation error:

fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f182d29a080 pc=0x15f8983]
goroutine 131 [running, locked to thread]:
runtime.throw({0x1aaba05?, 0x1d7ec00?})
	GOROOT/src/runtime/panic.go:992 +0x71 fp=0xc00194d910 sp=0xc00194d8e0 pc=0x4361b1
runtime.sigpanic()
	GOROOT/src/runtime/signal_unix.go:825 +0x2ec fp=0xc00194d960 sp=0xc00194d910 pc=0x44c52c
github.com/lirm/aeron-go/aeron/flyweight.(*Int64Field).Get(0xc0003bd290)
	external/com_github_lirm_aeron_go/aeron/flyweight/fields.go:72 +0x23 fp=0xc00194d978 sp=0xc00194d960 pc=0x15f8983
github.com/lirm/aeron-go/aeron.(*Image).Close(0xc004e72280)
	external/com_github_lirm_aeron_go/aeron/image.go:265 +0xc8 fp=0xc00194da50

**Comment by ethanf** [comment]
Haven't seen this before. Is this reproducible? Make sure that there hasn't been an Aeron timeout, which would mean that the shared image memory has been cleaned up.
